@server_HostAddress = https://localhost:7072

### Create user - success
POST {{server_HostAddress}}/api/User
Accept: application/json
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Smith"
}

### Create user - error - name field empty
POST {{server_HostAddress}}/api/User
Accept: application/json
Content-Type: application/json

{
  "firstName": "",
  "lastName": "Smith"
}

### Create user - error - name char below min length 2
POST {{server_HostAddress}}/api/User
Accept: application/json
Content-Type: application/json

{
  "firstName": "J ",
  "lastName": "Smith"
}

### Create user - error - name char exceeds max length 20
POST {{server_HostAddress}}/api/User
Accept: application/json
Content-Type: application/json

{
  "firstName": "Johnasdasdasdasdasdas",
  "lastName": "Smith"
}

### Create user - error - non letter in name
POST {{server_HostAddress}}/api/User
Accept: application/json
Content-Type: application/json

{
  "firstName": "John1",
  "lastName": "Smith"
}
